### ISSUE TITLE
Brilliant Idea!

### ISSUE THREAD

**Issue by LeonCheung** [chromoly/quadview_move#1]
God this is extremely convenient and useful! BTW, not sure if more layout presets can be possible here? For example here is the layout switcher from another software:

![qq 20160526143252](https://cloud.githubusercontent.com/assets/494788/15565732/338e294c-234f-11e6-8cfa-e4d8ae751af5.png)

Just brainstorming. :P  
If not possible, just close this issue.  :)

**Comment by chromoly** [comment]
addonでは無理だと思います
